import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google';
import "./globals.css";
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'], weight: ['400', '500','600', '700'],variable: '--font-inter' });

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500','600', '700'], variable: '--font-poppins' });

export const metadata: Metadata = {
  title: "Keerti Bhatnagar",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies(); // Await the cookies
  const theme = cookieStore.get("theme")?.value || "dark";
  return (
    <html lang="en" className={theme}>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
